<a href="https://colab.research.google.com/github/zbc89631412/svbrdf/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import os
import cv2
import matplotlib as plt
import numpy as np
from sklearn.metrics import mean_squared_error
from math import sqrt
import PIL
import statistics

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
path_prefix = "/content/gdrive/MyDrive/final"

import sys
sys.path.insert(1, path_prefix)

Mounted at /content/gdrive


In [ ]:

filePath = '/content/gdrive/content/gdrive/MyDrive/final/model2_real_output'
print(os.walk(filePath))
for i,j,k in os.walk(filePath):
    

<generator object walk at 0x7f08e39c5850>


In [ ]:


array_of_img = [] # this if for store all of the image data
filename_array = []
# this function is for read image,the input is directory name
def read_directory(directory_name):
    # this loop is for read each image in this foder,directory_name is the foder name with images.
    for filename in os.listdir(directory_name):
        #print(filename) #just for test
        #img is used to store the image data
        img = cv2.imread(directory_name+"/"+filename)
        print(filename)
        #cv2.imshow( img)
        array_of_img.append(img)
        filename_array.append(filename)
        #plt.pyplot.imshow(filename)
        #print(array_of_img)
    return array_of_img,filename_array


crop output_svbrdf_reference

In [ ]:
img_array,filename_list = read_directory("/content/gdrive/MyDrive/final/output_svbrdf_reference")
for img in img_array:
    print(img.shape)
#img = cv2.imread("data/testBlended/0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1.png")
#print(img.shape)
count = 0
for img in img_array:
  filename_list[count] = filename_list[count].split('.')[0]
  cropped1 = img[0:256, 0:256]
  cv2.imwrite("/content/gdrive/MyDrive/final/reference_cropped/"+filename_list[count]+"_normal.png", cropped1)
  cropped2 = img[0:256,256:512]
  cv2.imwrite("/content/gdrive/MyDrive/final/reference_cropped/"+filename_list[count]+"_diffuse.png", cropped2)
  cropped3 = img[0:256,512:768]
  cv2.imwrite("/content/gdrive/MyDrive/final/reference_cropped/"+filename_list[count]+"_roughness.png", cropped3)
  cropped4 = img[0:256,768:1024]
  cv2.imwrite("/content/gdrive/MyDrive/final/reference_cropped/"+filename_list[count]+"_specular.png", cropped4)
  count += 1

crop model 2

In [ ]:

array_of_img = [] # this if for store all of the image data
filename_array = []
# this function is for read image,the input is directory name
def read_directory(directory_name):
    # this loop is for read each image in this foder,directory_name is the foder name with images.
    for second_filename in os.listdir(directory_name):
        #print(filename) #just for test
        #img is used to store the image data
        #print(second_filename)
        #second_filename = second_filename.split("_refine")
        if second_filename.find("_refine")!=-1:
          img = cv2.imread(directory_name+"/"+second_filename+"/"+"output_199.png")
          #print(img)
          print(second_filename)
          array_of_img.append(img)
          second_filename = second_filename.split("_refine")
          filename_array.append(second_filename[0])
        # for filename in os.listdir(second_filename):

        #   if filename.find("_refine")!=-1:
        #     filename = filename.split("_refine")
        #     print(file_name)
        #     img = cv2.imread(directory_name+"/"+filename+"/"+"output_199,png")
        #     array_of_img.append(img)
        #     filename_array.append(filename)
          
        #plt.pyplot.imshow(filename)
        #print(array_of_img)
    return array_of_img,filename_array

In [ ]:
img_array,filename_list = read_directory("/content/gdrive/MyDrive/final/testBlended_result")
# for img in img_array:
#     print(img.shape)
#img = cv2.imread("data/testBlended/0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1.png")
#print(img.shape)
count = 0
for name in filename_list:
  print(name)
for img in img_array:
  #filename_list[count] = filename_list[count].split('.')[0]
  cropped1 = img[0:256, 0:256]
  cv2.imwrite("/content/gdrive/MyDrive/final/model2_cropped/"+filename_list[count]+"_normal.png", cropped1)
  cropped2 = img[0:256,256:512]
  cv2.imwrite("/content/gdrive/MyDrive/final/model2_cropped/"+filename_list[count]+"_diffuse.png", cropped2)
  cropped3 = img[0:256,512:768]
  cv2.imwrite("/content/gdrive/MyDrive/final/model2_cropped/"+filename_list[count]+"_roughness.png", cropped3)
  cropped4 = img[0:256,768:1024]
  cv2.imwrite("/content/gdrive/MyDrive/final/model2_cropped/"+filename_list[count]+"_specular.png", cropped4)
  count += 1

model 3

In [ ]:
directory_name ="/content/gdrive/MyDrive/final/ALL_5D_Render_Syn_testBlended"
for filename in os.listdir(directory_name):
  #print(filename)
  if filename.find("Diff Fake")!=-1:
    img = cv2.imread(directory_name+"/"+filename)
    #print(filename)
    #print(img)
    filename = filename.split(".")
    print(filename[0])
    cv2.imwrite("/content/gdrive/MyDrive/final/model3_cropped/"+filename[0]+".png",img)
  elif filename.find("Normal Fake")!=-1:
    img = cv2.imread(directory_name+"/"+filename)
    filename = filename.split(".")
    cv2.imwrite("/content/gdrive/MyDrive/final/model3_cropped/"+filename[0]+".png",img)
  elif filename.find("Rough Fake")!=-1:
    img = cv2.imread(directory_name+"/"+filename)
    filename = filename.split(".")
    cv2.imwrite("/content/gdrive/MyDrive/final/model3_cropped/"+filename[0]+".png",img)
  elif filename.find("Spec Fake")!=-1:
    img = cv2.imread(directory_name+"/"+filename)
    filename = filename.split(".")
    cv2.imwrite("/content/gdrive/MyDrive/final/model3_cropped/"+filename[0]+".png",img)

DisabledFunctionError: ignored

In [ ]:
directory_name = "/content/gdrive/MyDrive/final/images"
for filename in os.listdir(directory_name):
  #print(filename)
  if filename.find("outputs-0-")!=-1:
    print(filename)
    img = cv2.imread(directory_name+"/"+filename)
    filename = filename.replace("outputs-0-","normal")
    cv2.imwrite("/content/gdrive/MyDrive/final/model1_cropped/"+filename,img)
  elif filename.find("outputs-1-")!=-1:
    img = cv2.imread(directory_name+"/"+filename)
    filename = filename.replace("outputs-1-","diffuse")
    cv2.imwrite("/content/gdrive/MyDrive/final/model1_cropped/"+filename,img)
  elif filename.find("outputs-2-")!=-1:
      img = cv2.imread(directory_name+"/"+filename)
      filename = filename.replace("outputs-2-","roughness")
      cv2.imwrite("/content/gdrive/MyDrive/final/model1_cropped/"+filename,img)
  elif filename.find("outputs-3-")!=-1:
    filename = filename.replace("outputs-3-","spec")
    cv2.imwrite("/content/gdrive/MyDrive/final/model1_cropped/"+filename,img)


In [ ]:
from google.colab.patches import cv2_imshow
file_path = "/content/gdrive/MyDrive/final/images/0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1_input_label-inputs.png"
img = cv2.imread(file_path,0)
print(img)

[[141 148 148 ... 128 129 128]
 [142 142 141 ... 123 119 131]
 [143 135 143 ... 111 115 129]
 ...
 [155 158 158 ... 132 142 139]
 [158 158 157 ... 131 133 142]
 [157 158 152 ... 133 132 135]]


In [ ]:
def rmsdiff(I1, I2):
    print(I1.shape[0],I2.shape[1])
    ones_matrix = np.ones([I1.shape[0],I1.shape[1]])
    x1 = I1 + ones_matrix
    x2 = I2 + ones_matrix
    if x1.min()<=0:
      print(x1.min())

    # rmse = np.sum((np.log(I1 + ones_matrix) - np.log()) ** 2)
    # print("log(I1+1) is "+np.log(I1 + ones_matrix))
    # print(rmse)
    # rmse = np.sqrt(rmse)
    # rmse = rmse / float(I1.shape[0] * I2.shape[1])
    # rmse = np.sqrt(rmse)
    
    return rmse

In [ ]:
!pip install python-docx

In [ ]:
import docx
from google.colab import files

In [ ]:
def read_img(directory_name):
  img = cv2.imread(directory_name,0)
  return img

In [ ]:
def filename_sort(directory_name):
  file_name_list = []
  for file_name in os.listdir(directory_name):
    file_name_list.append(file_name)
  file_name_list.sort()
  return file_name_list

In [ ]:
file=docx.Document()

reference_directory_name = "/content/gdrive/MyDrive/final/reference_cropped"

features_directory_name=["/content/gdrive/MyDrive/final/model1_cropped","/content/gdrive/MyDrive/final/model2_cropped","/content/gdrive/MyDrive/final/model3_cropped"]
gt = filename_sort(reference_directory_name)
# model1 = filename_sort(features_directory_name[0])
# model2 = filename_sort(features_directory_name[1])
# model3 = filename_sort(features_directory_name[2])
print(gt)
model_count = 0
feature_count = 0
image_count = 0
rmse_file=docx.Document()
for model in features_directory_name:
   fake_filename_list = filename_sort(model)
   print(fake_filename_list)
   rmse_diff = []
   rmse_normal =[]
   rmse_spec = []
   rmse_roughness=[]
   table = file.add_table(rows=84, cols=4, style="Table Grid")
   row=0
   file.add_paragraph("new model")
   for fake_img_name,gt_img_name in zip(fake_filename_list,gt):
     fake_img = cv2.imread(model+"/"+fake_img_name,0)
     gt_img = cv2.imread(reference_directory_name+"/"+gt_img_name,0)
     rmse = rmsdiff(fake_img,gt_img)
     if gt_img_name.find("diffuse")!=-1:
       rmse_diff.append(rmse)
       #table.cell(row,0).text = str(rmse)
     if gt_img_name.find("normal")!=-1:
       rmse_normal.append(rmse)
       #table.cell(row,1).text=str(rmse)
     if gt_img_name.find("specular")!=-1:
       rmse_spec.append(rmse)
       #table.cell(row,2).text=str(rmse)
     if gt_img_name.find("roughness")!=-1:
       rmse_roughness.append(rmse)
       #table.cell(row,3).text=str(rmse)
   for i in range(len(rmse_diff)):
     table.cell(i,0).text =str(round(rmse_diff[i],4))
     table.cell(i,1).text = str(round(rmse_normal[i],4))
     table.cell(i,2).text = str(round(rmse_roughness[i],4))
     table.cell(i,3).text = str(round(rmse_spec[i],4))
  #  table.cell(len(rmse_diff),0)=str(round(np.mean(rmse_diff),4))
  #  table.cell(len(rmse_normal),1)=str(round(np.mean(rmse_normal),4))
  #  table.cell(len(rmse_roughness),2)=str(round(np.mean(rmse_roughness),4))
  #  table.cell(len(rmse_spec),3)=str(round(np.mean(rmse_spec),4))
file.save("/content/gdrive/MyDrive/final/rmse.docx")
   
    
   
    
    

['0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1_diffuse.png', '0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1_normal.png', '0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1_roughness.png', '0000001;PolishedMarbleFloor_01Xmetal_bumpy_squares;1X1_specular.png', '0000002;PolishedMarbleFloor_01Xmetal_bumpy_squares;3Xdefault_diffuse.png', '0000002;PolishedMarbleFloor_01Xmetal_bumpy_squares;3Xdefault_normal.png', '0000002;PolishedMarbleFloor_01Xmetal_bumpy_squares;3Xdefault_roughness.png', '0000002;PolishedMarbleFloor_01Xmetal_bumpy_squares;3Xdefault_specular.png', '0000003;PolishedMarbleFloor_01Xmetal_bumpy_squares;0X0_diffuse.png', '0000003;PolishedMarbleFloor_01Xmetal_bumpy_squares;0X0_normal.png', '0000003;PolishedMarbleFloor_01Xmetal_bumpy_squares;0X0_roughness.png', '0000003;PolishedMarbleFloor_01Xmetal_bumpy_squares;0X0_specular.png', '0000004;PolishedMarbleFloor_01Xmetal_bumpy_squares;4X2_diffuse.png', '0000004;PolishedMarbleFloor_01Xmetal_bumpy_squares;4X2_nor

In [ ]:
test = np.array([1,2,3,4])
test = test.reshape(2,2)
print(test)
one_m = np.ones([2,2])
print(test+one_m)

[[1 2]
 [3 4]]
[[2. 3.]
 [4. 5.]]
